# Generated by Django 6.0.1 on 2026-02-11 08:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_usercourseprogress_certificate_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourseprogress',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='usercourseprogress',
            name='certificate_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
