# Generated by Django 5.2.6 on 2025-09-14 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miniproject',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('inprogress', 'In Progress'), ('completed', 'Completed')], default='assigned', max_length=20),
        ),
    ]
