# Generated by Django 6.0.1 on 2026-02-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_savedjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.TextField(blank=True, help_text='Comma-separated skills (e.g. Python, Django, SQL)', null=True),
        ),
    ]
