# Generated by Django 6.0.1 on 2026-02-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_role_customuser_subscription_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pending_downgrade',
            field=models.CharField(blank=True, choices=[('free', 'Free'), ('pro', 'Pro'), ('pro_plus', 'Pro Plus')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
