# Generated by Django 6.0.1 on 2026-02-09 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_customuser_pending_downgrade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_optimizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
